DROP TABLE IF EXISTS `auction`;
CREATE TABLE `auction` (
  `id` CHAR(26) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `close_at` DATETIME NOT NULL,
  `owner_id` VARCHAR(50) NOT NULL,
  `owner_name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `bidding`;
CREATE TABLE `bidding` (
  `id` CHAR(26) NOT NULL,
  `auction_id` CHAR(26) NOT NULL,
  `amount` BIGINT(20) NOT NULL,
  `bidder_id` VARCHAR(50) NOT NULL,
  `bidder_name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`auction_id`) REFERENCES auction(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
