version: "3.4"
services:
  builder:
    build:
      context: ../
      dockerfile: builder/Dockerfile
    volumes:
      - ../src:/app/src
      - ../rdsdata_mapper_derive/src:/app/rdsdata_mapper_derive/src
      - ../rdsdata_mapper/src:/app/rdsdata_mapper/src
      - ../artifact:/artifact
